Vagrant.configure("2") do |config|

#  if Vagrant.has_plugin?("vagrant-proxyconf")
#    config.proxy.http     = "http://10.0.2.2:3128/"
#    config.proxy.https    = "http://10.0.2.2:3128/"
#    config.proxy.no_proxy = "localhost,127.0.0.1,10.0.2.2"
#  end

  config.vm.define "workstation" do |atomic|
    atomic.vm.box = "ubuntu/bionic64"
    atomic.vm.hostname = "workstation"
    atomic.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2201
    atomic.vm.network "private_network", ip: "192.168.100.10", virtualbox__intnet: "intra"
    atomic.vm.provision "shell", inline: <<-SHELL
      apt update
      apt upgrade -y
    SHELL
    atomic.vm.provision "chef_solo" do |chef|
      chef.version = "14.12.9"
      chef.add_recipe "chefdk"
    end
  end

  config.vm.define "target" do |atomic|
    atomic.vm.box = "ubuntu/bionic64"
    atomic.vm.hostname = "target"
    atomic.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2202
    atomic.vm.network "private_network", ip: "192.168.100.11", virtualbox__intnet: "intra"
    atomic.vm.provision "shell", inline: <<-SHELL
      apt update
      apt upgrade -y
    SHELL
  end
end
